import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { fontsSize } from '../../theme/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  center: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  headerRight: {
    width: 32,
  },
  backButton: {
    padding: 4,
  },
  matchCard: {
    backgroundColor: colors.cardBackgroud,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 16,
    padding: 16,
  },
  statusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  statusBadge: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusLive: {
    backgroundColor: colors.participantBackgroud + '20',
  },
  statusUpcoming: {
    backgroundColor: colors.usersIconBackground + '20',
  },
  statusCompleted: {
    backgroundColor: colors.textSecondary + '20',
  },
  statusText: {
    fontSize: fontsSize.small,
    fontWeight: '600',
  },
  statusTextLive: {
    color: colors.participantBackgroud,
  },
  statusTextUpcoming: {
    color: colors.usersIconBackground,
  },
  statusTextCompleted: {
    color: colors.textSecondary,
  },
  liveIndicator: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  liveDot: {
    backgroundColor: colors.participantBackgroud,
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  liveText: {
    color: colors.participantBackgroud,
    fontSize: 13,
    fontWeight: '700',
  },
  teamsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  teamBlock: {
    alignItems: 'center',
    flex: 1,
  },
  teamAvatar: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    marginBottom: 8,
    width: 48,
  },
  teamAvatarText: {
    color: colors.primaryText,
    fontSize: 16,
    fontWeight: '700',
  },
  teamName: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 6,
    textAlign: 'center',
  },
  vsText: {
    color: colors.textSecondary,
    fontSize: 18,
    fontWeight: '600',
  },
  setScore: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
  },
  infoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 6,
  },
  infoText: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  setsLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 8,
  },
  section: {
    backgroundColor: colors.cardBackgroud,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 16,
    padding: 16,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: fontsSize.medium,
    fontWeight: '600',
    marginBottom: 12,
  },
  setRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  setNumber: {
    color: colors.textSecondary,
    fontSize: fontsSize.medium,
    width: 50,
  },
  setScores: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'center',
  },
  setScoreA: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  setScoreB: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  setDash: {
    color: colors.textSecondary,
    fontSize: 16,
    marginHorizontal: 8,
  },
  winScore: {
    color: colors.participantBackgroud,
  },
  setStatusBadge: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  setStatusLive: {
    backgroundColor: colors.participantBackgroud + '20',
  },
  setStatusCompleted: {
    backgroundColor: colors.textSecondary + '20',
  },
  setStatusText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '500',
  },
  inlineEditContainer: {
    backgroundColor: colors.inputField,
    borderRadius: 10,
    marginBottom: 8,
    marginTop: 4,
    padding: 12,
  },
  inlineEditTitle: {
    color: colors.textPrimary,
    fontSize: fontsSize.medium,
    fontWeight: '600',
    marginBottom: 12,
  },
  winnerBanner: {
    alignItems: 'center',
    backgroundColor: colors.participantBackgroud + '15',
    borderRadius: 10,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginBottom: 16,
    paddingVertical: 12,
  },
  winnerText: {
    color: colors.participantBackgroud,
    fontSize: 15,
    fontWeight: '600',
  },
  startMatchBtn: {
    alignItems: 'center',
    backgroundColor: colors.participantBackgroud,
    borderRadius: 10,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginBottom: 12,
    paddingVertical: 14,
  },
  startMatchBtnText: {
    color: colors.primaryText,
    fontSize: 15,
    fontWeight: '600',
  },
  editSetBtn: {
    marginLeft: 8,
  },
  scoreSection: {
    backgroundColor: colors.cardBackgroud,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 16,
    padding: 16,
  },
  scoreInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  scoreInputBlock: {
    alignItems: 'center',
    flex: 1,
  },
  scoreTeamName: {
    color: colors.textPrimary,
    fontSize: fontsSize.medium,
    fontWeight: '500',
    marginBottom: 12,
    textAlign: 'center',
  },
  scoreControls: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  scoreBtn: {
    alignItems: 'center',
    backgroundColor: colors.border,
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  scoreValue: {
    color: colors.textPrimary,
    fontSize: 32,
    fontWeight: '700',
    minWidth: 50,
    textAlign: 'center',
  },
  scoreActions: {
    gap: 12,
  },
  saveScoreBtn: {
    alignItems: 'center',
    backgroundColor: colors.border,
    borderRadius: 10,
    paddingVertical: 14,
  },
  saveScoreBtnText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '600',
  },
  completeSetBtn: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 10,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    paddingVertical: 14,
  },
  completeSetBtnText: {
    color: colors.primaryText,
    fontSize: 15,
    fontWeight: '600',
  },
  tieWarning: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 4,
    textAlign: 'center',
  },
  errorText: {
    color: colors.error,
    fontSize: fontsSize.medium,
    marginBottom: 8,
    textAlign: 'center',
  },
  modalOverlay: {
    backgroundColor: colors.appBackground + '80',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.cardBackgroud,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '600',
  },
  modalLabel: {
    color: colors.textPrimary,
    fontSize: fontsSize.medium,
    fontWeight: '500',
    marginBottom: 8,
  },
  datePickerBtn: {
    alignItems: 'center',
    backgroundColor: colors.cardBackgroud,
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
    padding: 14,
  },
  datePickerText: {
    color: colors.textPrimary,
    fontSize: fontsSize.medium,
  },
  setsInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 20,
    justifyContent: 'center',
    marginBottom: 20,
  },
  setsValue: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: '700',
    minWidth: 40,
    textAlign: 'center',
  },
});