export const APP_STRINGS = {
  app: {
    name: 'SportsCarnival',
    loginTagline: 'Manage your events',
    registerTagline: 'Join the competition',
  },
  auth: {
    welcomeBack: 'Welcome Back',
    signInSubtitle: 'Sign in to continue to your account',
    createAccount: 'Create Account',
    signUpSubtitle: 'Get started with your sports journey',
    resetPassword: 'Reset Password',
    createNewPasswordTagline: 'Create a new password for your account',
    somethingWentWrong: 'Something went wrong. Please try again.',
    loginFailed: 'Login failed',
  },
  common: {
    success: 'Success',
    error: 'Error',
    yes: 'Yes',
    no: 'No',
  },
  buttons: {
    createAccount: 'Create Account',
    signIn: 'Sign In',
    updatePassword: 'Update Password',
    forgotPassword: 'Forgot Password?',
    signUp: 'Sign Up',
    retry: 'Retry',
    cancel: 'Cancel',
    continue: 'Continue',
    deleteAll: 'Delete All',
  },
  labels: {
    email: 'Email',
    name: 'Name',
    newPassword: 'New Password',
    password: 'Password',
    confirmPassword: 'Confirm New Password',
  },
  footer: {
    noAccount: "Don't have an account?",
    accountAlready: 'Already have an account?',
  },
  placeHolders: {
    email: 'Enter your email',
    password: 'Enter your password',
    fullName: 'Enter your full name',
    createPassword: 'Create a password',
    enterPassword: 'Enter password',
    newPassword: 'Enter new password',
    confirmNewPassword: 'Confirm New Password',
    format: 'Format (Singles / Doubles)',
    teamName: 'Enter team name',
    captainName: 'Enter captain name',
    maxPlayers: 'Enter max players',
    playerName: 'Player Name',
    gender: 'Gender',
    prizeForFirst: 'Enter prize for first position',
    prizeForSecond: 'Enter prize for second position',
    prizeForThird: 'Enter prize for third position',
    rules: 'Enter rules separated by comma',
    searchTeams: 'Search Teams...',
    searchFixtures: 'Search Fixtures...',
    searchUsers: 'Search users by name or email...',
    logisticRequirements: 'Logistic Requirements',
    venue: 'Venue',
    date: 'YYYY-MM-DD',
    loadingSports: 'Loading sports...',
    selectSports: 'Select sport',
    sportsName: 'Sports Name',
    eventName: 'Event Name',
    registrationDeadline: 'Select registration deadline',
  },
  userScreen: {
    allUsers: 'All Users',
    addUser: 'Add User',
    noUsersFound: 'No users found',
    createUser: 'Create User',
    editUser: 'Edit User',
    saveChanges: 'Save Changes',
    assignRole: 'Assign Role',
    activateUser: 'Activate User',
    deactivateUser: 'Deactivate User',
    newPasswordOptional: 'Leave blank to keep current password',
  },
  roleSelection: {
    chooseRole: 'Choose your role',
    heading: 'How will you participate?',
    subHeading:
      'Select your role to customize your experience. You can change this later in the settings.',
  },
  adminScreens: {
    pendingRequest: 'Pending Request',
    totalRequest: 'Total Request',
    greeting: 'Hello, Admin! 👋',
    totalEvents: 'Total Events',
    activeUsers: 'Active Users',
    team: 'Teams',
    matchesToday: 'Matches Today',
    quickActions: 'Quick Actions',
    addEvent: 'Add Event',
    addUser: 'Add User',
    settings: 'Settings',
    liveMatches: 'Live Matches',
    raiseEventRequest: 'Request',
    bell: 'Notifications',
  },
  organizerScreens: {
    greeting: 'Hello, Organizer! 👋',
    myEvents: 'My Events',
    totalRegistrations: 'Total\nRegistrations',
    teamsRegistered: 'Teams\nRegistered',
    liveMatches: 'Live Matches',
    createEvent: 'Create Event',
    reviewTeams: 'Review Teams',
    upcomingMatches: 'Upcoming Matches',
  },
  participantScreens: {
    greeting: 'Hello, Participant! 👋',
    myEvents: 'My Events',
    myTeam: 'My Team',
    matchesPlayed: 'Matches\nPlayed',
    wins: 'Wins',
    captain: 'Captain',
    failedToLoadData: 'Failed to load participant data',
  },
  eventScreen: {
    eventManage: 'Tap an event to manage',
    editEvent: 'Edit Event',
    deleteEvent: 'Delete Event',
    createEvent: 'Create Event',
    all: 'All',
    live: 'Live',
    open: 'Open',
    upcoming: 'Upcoming',
    eventName: 'Event Name',
    sportName: 'Sport Name',
    format: 'Format',
    date: 'Date',
    time: 'Time',
    venue: 'Venue',
    totalParticipants: 'Total Participants',
    deleteEventConfirmation: 'Are you sure you want to delete event?',
    saveChanges: 'Save Changes',
    allEvents: 'All Events',
    myEvents: 'My Events',
    teams: 'Teams',
    noEventFound: 'No Event Found',
    eventNotFound: 'Event not found',
    failedToLoad: 'Failed to load event',
    teamsRegistered: ' Teams Registered',
    edit: 'Edit',
    register: 'Register',
    delete: 'Delete',
    vs: 'VS',
    registrationOpen: 'Registration Open',
    winRate: 'Win Rate',
    todaysMatches: "Today's Matches",
    noTeamsFound: 'No Teams Found',
    createTeam: 'Create Team',
    editTeam: 'Edit Team',
    teamName: 'Team Name',
    captainName: 'Captain Name',
    selectSport: 'Select Sport',
    maxPlayers: 'Max Players',
    registerForEvent: 'Register for Event',
    selectFormat: 'Select Format',
    noDescription: 'No description available.',
    rulesSharedSoon: 'Rules will be shared soon.',
    description: 'Description',
    rulesAndRegulations: 'Rules & Regulations',
    teamNotCreated: 'Teams not created yet',
    fixtureNotCreated: 'Fixtures not created yet',
    createFixtures: 'Create Fixtures',
    prizeNotAnnounced: 'No prizes announced yet.',
    position: 'Position',
    reward: 'Reward',
    standardRules: 'Standard tournament rules apply',
    registrationClosed: 'Registration Closed',
    createTeamFirst: 'Please create teams first.',
    prizeForFirst: 'Prize for first position',
    prizeForSecond: 'Prize for second position',
    prizeForThird: 'Prize for third position',
    eventCompleted: 'Event Completed',
    fixturesReady: 'Fixtures Ready',
    teamsCreated: 'Teams Created',
    final: 'Final',
    semiFinal: 'Semi-Final',
    quarterFinal: 'Quarter-Final',
    notEnoughCompletedMatches: 'Not Enough Completed Matches',
    noEnoughRegistrations: 'No Enough Registrations',
    eventFull: 'Event Full',
    slotsFull: 'Slots Full',
    noMoreSlots: 'No more slots available',
    registered: 'Registered',
    registrationSuccessfull: 'You have registered successfully',
    noTeamsRequired: 'No teams required for Singles format. Players will compete individually.',
    notEnoughSameGenderParticipants: 'Not enough same-gender participants',
    notEnoughSameGenderPairs: 'Not enough same-gender pairs',
    maleSlots: 'Male Slots',
    femaleSlots: 'Female Slots',
    notMatchesToday: 'No Matches Today',
    activeUserText: 'User can access the platform',
    inactiveUserText: 'User will not be able to sign in',
    abandoned: 'Abandoned',
    abandonedLabel: ' (Abandoned)',
    startMatch: 'Start Match',
    updateScore: 'Update Score',
    saveScore: 'Save Score',
    completeMatch: 'Complete Match',
    differentScores: 'Scores must be different to complete',
    note: 'Note',
    oddRegistrationsAlert: 'Odd number of participants; one may get a bye.',
    categoryAbandoned: 'Category Abandoned',
    categoryAbandonedDescription: 'This category has been abandoned.',
    categories: 'Categories',
    noRegisteredParticipants: 'No registered participants',
    prizes: 'Prizes',
    selectFormats: 'Select Format(s)',
    chooseFormat: 'Choose Format(s) to participate in',
    full: 'Event is full',
    individualMatches: 'Individual matches',
    teamOfPlayers: 'Team of players',
    teamCreationFailed: 'Failed to create teams. Please try again.',
    active: 'Active',
    inactive: 'Inactive',
    registrationDeadline: 'Registration Deadline',
    maxParticipants: 'Max Participants',
    organizer: 'Organizer',
    assignOrganizer: 'Assign Organizer',
    currentOrganizer: 'Current',
    noOrganizersAvailable: 'No organizers available.',
    assigning: 'Assigning...',
    assignOrganizerSuccess: 'Organizer assigned successfully!',
    assignOrganizerError: 'Failed to assign organizer.',
    publishEvent: 'Publish',
    publishError: 'Failed to publish event.',
    editAction: 'Edit',
    organizerAction: 'Organizer',
    registrationFailed: 'Registration failed',
    failedUserLoad: 'Failed to load users',
    womens: "Women's",
    mens: "Men's",
    mixed: 'Mixed',
  },
  eventFormScreen: {
    registrationDeadlineRequired: 'Registration deadline is required',
    deadlineBeforeStart: 'Deadline must be before the start date',
    eventUpdated: 'Event updated successfully!',
    eventCreated: 'Event created successfully!',
    cancelEvent: 'Cancel Event',
    cancelEventConfirm: 'Are you sure you want to cancel this event? This cannot be undone.',
    cancelNo: 'No',
    cancelYes: 'Yes, Cancel Event',
    eventCancelled: 'Event has been cancelled.',
    failedToCancel: 'Failed to cancel event',
    somethingWentWrong: 'Something went wrong',
    gender: 'Gender *',
    womens: "Women's",
    mens: "Men's",
    mixed: 'Mixed',
  },
  RequestScreen: {
    sportsName: 'Sports Name *',
    eventName: 'Event Name *',
    raiseRequest: 'Raise Request',
    editRequest: 'Edit Request',
    noRequestFound: 'No request found',
    updateRequest: 'Update Request',
    logisticRequirements: 'Logistic Requirements',
    venue: 'Requested Venue *',
    format: 'Format :',
    endDate: 'End Date : ',
    startDate: 'Start Date : ',
    endDateRequired: 'End Date *',
    startDateRequired: 'Start Date *',
    formatRequired: 'Format *',
    gender: 'Gender :',
    createEvent: 'Create Event',
    update: 'Updated :',
    updateRequired: 'Update',
    create: 'Create :',
    withdraw: 'Withdraw',
    operationsReviewerName: 'OperationsReviewerName :',
    remarks: 'Remarks :',
    logistics: 'Logistics :',
    approve: 'Approve',
    reject: 'Reject',
    enterRemarks: 'Enter Remarks',
    writeRemarks: 'Write remarks...',
    cancel: 'Cancel',
    submit: 'Submit',
    request: 'Request',
  },
  OperationScreen: {
    operation: 'Operation',
  },
  NotificationScreen: {
    notification: 'Notification',
    noNotification: 'No Notification yet',
    request: 'Request#',
    loadingNotification: 'Loading Notification...',
    retry: 'Retry',
    new: 'New',
  },
  EventRequestScreen: {
    request: 'Request',
  },
  fixtureScreen: {
    error: 'Error',
    cannotRegenerate: 'Cannot Regenerate',
    cannotRegenerateDesc: 'Fixtures cannot be regenerated once a match is live or completed.',
    regenerateFixtures: 'Regenerate Fixtures',
    regenerateFixturesDesc: 'All existing fixtures will be deleted and regenerated. Continue?',
    cannotDelete: 'Cannot Delete',
    cannotDeleteDesc: 'Fixtures cannot be deleted once a match is live or completed.',
    deleteAllFixtures: 'Delete All Fixtures',
    deleteAllFixturesDesc:
      'Deleting this fixture will delete ALL fixtures for this category. You can regenerate them after.',
    failedToDeleteFixtures: 'Failed to delete fixtures',
    matchPrefix: 'Match ',
    schedule: 'Schedule',
    tbd: 'TBD',
  },
  matchScreen: {
    error: 'Error',
    cannotStartMatch: 'Cannot Start Match',
    cannotStartMatchDesc:
      'All matches in the previous round must be completed before starting this match.',
    failedToStartMatch: 'Failed to start match',
    failedToScheduleMatch: 'Failed to schedule match',
    failedToSaveScore: 'Failed to save score',
    scheduleConflict: 'This time slot conflicts with another match. Choose a different time.',
    invalidTotalSets: 'Total sets must be between 1 and 9 (odd numbers only)',
    scheduleDateRange: (from: string, to: string) => `Match must be between ${from} and ${to}`,
    starting: 'Starting...',
    saving: 'Saving...',
    confirmSchedule: 'Confirm Schedule',
    scheduleMatch: 'Schedule Match',
    reschedule: 'Reschedule',
    totalSetsLabel: 'Total Sets (1–10)',
    goLive: 'Go Live →',
    updateScore: 'Update Score →',
    viewResult: 'View Result →',
    viewScore: 'View Score →',
    startMatchBtn: 'Start Match (Go Live)',
    tapToWatchLive: 'Tap to watch live →',
    saveEdit: 'Save Edit',
    saveScore: 'Save Score',
    completeSet: 'Complete Set',
    tieWarning: 'Scores must differ to complete set',
    matchNotFound: 'Match not found',
    matchDetails: 'Match Details',
    bestOf: (n: number) => `Best of ${n} sets`,
    winner: (name: string) => `Winner: ${name}`,
    setLabel: (n: number) => `Set ${n}`,
    editSetLabel: (n: number) => `Edit Set ${n}`,
    setScoreLabel: (n: number) => `Set ${n} Score`,
    sets: 'Sets',
    date: 'Date',
    time: 'Time',
    vs: 'vs',
  },
  goLiveModal: {
    title: 'Go Live',
    selectSets: 'Select Number of Sets',
    mustBeOdd: '(Best of — must be odd)',
    bestOfSummary: (n: number, wins: number) => `Best of ${n} — first to ${wins} wins`,
    confirmGoLive: 'Confirm & Go Live',
    failedToGoLive: 'Failed to go live',
    livePollFailed : 'Live poll failed:',
    minimumParticipants: (n: number) => `Minimum ${n} participants required`,
    teamsAndFixturesCreated: 'Teams and fixtures created successfully',
  },
  rescheduleModal: {
    title: 'Reschedule Match',
    selectMatch: 'Select Match to Reschedule',
    noUpcomingMatches: 'No upcoming matches to reschedule',
    selectDateTime: 'Select New Date & Time',
    selectMatchFirst: 'Select a match first',
    noteShift: 'All matches scheduled after this one will also shift.',
    confirm: 'Confirm Reschedule',
    rescheduling: 'Rescheduling...',
    success: 'Match rescheduled successfully',
    failed: 'Failed to reschedule match',
    button: 'Reschedule',
    date: 'Date',
    time: 'Time',
  },
  registrationScreen: {
    alreadyRegistered: 'Already Registered',
    alreadyRegisteredForFormat: (gender: string, format: string) =>
      `You are already registered for ${gender} ${format}.`,
    categoryFullAlert: (gender: string, format: string) =>
      `${gender} ${format} category is full.`,
    notAllowed: 'Not Allowed',
    cannotSwitchGender: (registered: string, newGender: string) =>
      `You are already registered as ${registered}. You cannot register for ${newGender}.`,
    alreadyRegisteredMultiple: (formats: string) =>
      `You are already registered for: ${formats}`,
    failedToLoadEvent: 'Failed to load event details',
    categoryNotFound: (gender: string, format: string) =>
      `Category not found for ${gender} ${format}`,
    registeredBadge: 'Registered',
  },
  stores: {
    userStoreError: 'useUserStore must be used inside UserProvider',
    eventRequestStoreError: 'useEventRequestStore must be used inside EventRequestProvider',
    somethingWentWrong: 'Something went wrong',
  },
  eventStatusTabs: {
    all: 'All',
  },
};